export const decorativeBG = [
  {
    id: 1,
    image: "/Post_Images/1.jpg",
  },
  { id: 2, image: "/Post_Images/2.jpg" },
  { id: 3, image: "/Post_Images/3.jpg" },
  { id: 4, image: "/Post_Images/4.jpg" },
  { id: 5, image: "/Post_Images/5.jpg" },
  { id: 6, image: "/Post_Images/6.jpg" },
  { id: 7, image: "/Post_Images/7.jpg" },
  { id: 8, image: "/Post_Images/8.jpg" },
  { id: 9, image: "/Post_Images/9.jpg" },
  { id: 10, image: "/Post_Images/10.jpg" },
  { id: 11, image: "/Post_Images/12.jpg" },
  { id: 12, image: "/Post_Images/12.jpg" },
  { id: 13, image: "/Post_Images/13.jpg" },
  { id: 14, image: "/Post_Images/14.jpg" },
  { id: 16, image: "/Post_Images/16.jpg" },
  { id: 17, image: "/Post_Images/17.jpg" },
  { id: 18, image: "/Post_Images/18.jpg" },
  { id: 19, image: "/Post_Images/19.jpg" },
  { id: 20, image: "/Post_Images/20.jpg" },
  { id: 21, image: "/Post_Images/21.jpg" },
  { id: 22, image: "/Post_Images/22.jpg" },
  { id: 24, image: "/Post_Images/24.jpg" },
  { id: 25, image: "/Post_Images/25.jpg" },
];
export const gradientBG = [
  {
    id: 26,
    image: "/Post_Images/26.jpg",
  },
  {
    id: 27,
    image: "/Post_Images/27.jpg",
  },
  {
    id: 28,
    image: "/Post_Images/28.jpg",
  },
  {
    id: 29,
    image: "/Post_Images/29.jpg",
  },
  {
    id: 30,
    image: "/Post_Images/30.jpg",
  },
  {
    id: 31,
    image: "/Post_Images/31.jpg",
  },
  {
    id: 32,
    image: "/Post_Images/32.jpg",
  },
  {
    id: 33,
    image: "/Post_Images/33.jpg",
  },
  {
    id: 34,
    image: "/Post_Images/34.jpg",
  },
  // {
  //   id: 35,
  //   image: "/Post_Images/35.jpg",
  // },
];
export const solidBG = [
  { id: 36, colored: "red" },
  { id: 37, colored: "yellow" },
  { id: 38, colored: "pink" },
  { id: 39, colored: "green" },
  { id: 40, colored: "blue" },
  { id: 41, colored: "orange" },
  { id: 42, colored: "purple" },
  { id: 43, colored: "teal" },
  { id: 44, colored: "lime" },
  { id: 45, colored: "cyan" },
  { id: 46, colored: "indigo" },
  { id: 47, colored: "violet" },
  { id: 48, colored: "gray" },
  { id: 49, colored: "black" },
  { id: 50, colored: "white" },
  { id: 51, colored: "brown" },
  { id: 52, colored: "magenta" },
  { id: 53, colored: "gold" },
  { id: 54, colored: "silver" },
  { id: 55, colored: "navy" },
];
